Update apikey.md
timeplus-io/docs pull request #83
Opened 2023-09-02 13:57 UTC by heyitswei

Updated docs for Create API Key

2023-09-02 15:03 UTC, jovezhong commented on docs/apikey.md
> +<img width="1361" alt="api-key-avatar-1" src="https://github.com/timeplus-io/docs/assets/107260595/4aa9e9af-01e3-46e9-8724-aa10fde0da3e">
should not use assets in this way. Either need to checkin the image or use a public available image.

2023-09-02 15:04 UTC, jovezhong requested changes
use markdown syntax for inserting image and upload the images if it's part of the repo, or use external image link, such as from timeplus.com

2023-09-02 15:04 UTC, jovezhong commented on docs/apikey.md
> +<img width="1362" alt="api-key-settings-2" src="https://github.com/timeplus-io/docs/assets/107260595/efa73b94-f7ba-4b1f-b7b8-7a1f3c347662">
wrong

2023-09-02 15:04 UTC, jovezhong commented on docs/apikey.md
> +<img width="1362" alt="api-key-dialog-3" src="https://github.com/timeplus-io/docs/assets/107260595/17c60d79-1bb3-4978-b707-c2955b5fce29">
wrong

2023-09-02 15:04 UTC, jovezhong commented on docs/apikey.md
> +<img width="1362" alt="api-key-copy-4" src="https://github.com/timeplus-io/docs/assets/107260595/509addcf-bb89-423b-b311-299c36e1e561">
wrong

2023-09-13 17:54 UTC, heyitswei commented
Closing this PR as these changes are duplicate

2023-09-13 17:54 UTC, closed without merging