Add Confluent UTM links
timeplus-io/docs pull request #86
Opened 2023-09-06 18:57 UTC by heyitswei

Add 2 UTM links to mentions of Confluent Cloud

2023-09-06 19:03 UTC, jovezhong commented
Why there are new files for confluent-cloud-source and apikey? They are already in main branch

2023-09-06 19:04 UTC, heyitswei commented
Hi Jove, I think there are some duplicate files now

2023-09-06 19:16 UTC, jovezhong commented on docs/create-api-key.md
there is already a apikey.md

2023-09-06 19:17 UTC, jovezhong requested changes
Didn't use images correctly

2023-09-13 15:29 UTC, heyitswei commented
Closing this PR as there are duplicate edits made - will send a new PR without duplicates

2023-09-13 15:29 UTC, closed without merging